name: Label Copilot Workspace PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Label PR
        uses: actions/github-script@v7
        if: contains(github.event.pull_request.body, 'Copilot Workspace session')
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Copilot Workspace']
            })

